// Code generated by hertz generator.

package about

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _aboutMw() []app.HandlerFunc {
	// your code...
	return nil
}
