path: Dockerfile
update_behavior:
  type: skip
body: |-
  FROM golang:alpine

  WORKDIR /opt/application

  ENV GOPROXY=https://goproxy.cn

  COPY go.mod go.sum .
  RUN go mod download

  COPY . /opt/application

  RUN go build -o app cmd/

  FROM alpine:latest

  ENV GO_ENV=online

  RUN set sed -i 's/dl-cdn.alpinelinux.org/mirrors.aliyun.com/g' /etc/apk/repositories \
  apk --no-cache add ca-certificates

  WORKDIR /opt/application

  COPY --from=0 /opt/application/app ./
  COPY conf /opt/application/conf

  CMD ["./app"]
