kitex_gen_user:
	kitex --thrift-plugin validator -module github.com/cloudwego/biz-demo/easy_note idl/user.thrift # execute in the project root directory

kitex_gen_note:
	kitex --thrift-plugin validator -module github.com/cloudwego/biz-demo/easy_note idl/note.thrift # execute in the project root directory