 CREATE DATABASE IF NOT EXISTS `cart`  
    DEFAULT CHARACTER SET = 'utf8mb4';;

CREATE DATABASE IF NOT EXISTS `checkout`
    DEFAULT CHARACTER SET = 'utf8mb4';

CREATE DATABASE IF NOT EXISTS `order`
    DEFAULT CHARACTER SET = 'utf8mb4';

CREATE DATABASE IF NOT EXISTS `payment`
    DEFAULT CHARACTER SET = 'utf8mb4';

CREATE DATABASE IF NOT EXISTS `product`
    DEFAULT CHARACTER SET = 'utf8mb4';

CREATE DATABASE IF NOT EXISTS `user`
    DEFAULT CHARACTER SET = 'utf8mb4';