// Code generated by hertz generator.

package category

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _categoryMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _category0Mw() []app.HandlerFunc {
	// your code...
	return nil
}
